### ISSUE TITLE
cacheDirs is missing from cache operator CRD

### ISSUE THREAD

**Issue by mtparet** [juicedata/charts#142]
GIven https://juicefs.com/docs/csi/guide/cache-group-operator/#cache-group-configs 

```
apiVersion: juicefs.io/v1
kind: CacheGroup
metadata:
  name: cachegroup-sample
  namespace: default
spec:
  worker:
    template:
      nodeSelector:
        juicefs.io/cg-worker: "true"
      image: juicedata/mount:ee-5.1.1-1faf43b
      cacheDirs:
        - type: HostPath
          path: /var/jfsCache-0
        - type: PVC
          name: juicefs-cache-pvc
```

Error when trying applying it `Error from server (BadRequest): error when creating "tt": CacheGroup in version "v1" cannot be handled as a CacheGroup: strict decoding error: unknown field "spec.worker.template.cacheDirs"`

When looking at https://github.com/juicedata/charts/blob/main/charts/juicefs-cache-group-operator/crds/crd.yaml cacheDirs is not declared.
