### ISSUE TITLE
arm64 (multi platform) support

### ISSUE THREAD

**Issue by holygrolli** [juicedata/charts#21]
seems like the sidecars are not available as cross platform builds:
```
sidecars:
  livenessProbeImage:
    repository: quay.io/k8scsi/livenessprobe
    tag: "v1.1.0"
  nodeDriverRegistrarImage:
    repository: quay.io/k8scsi/csi-node-driver-registrar
    tag: "v1.1.0"
```

Did anyone try this successfully on an ARM64 system? I am running Ubuntu Server inside a qemu vm on my M1 Mac and it only downloads x86 images of livenessprobe and registrar.

Thanks!
